FROM node:latest

WORKDIR /career

# COPY ./package*.json ./

# RUN npm install


# COPY . .

# RUN pwd
# RUN ls


# RUN npm install next
 

EXPOSE 3000
# CMD 
CMD ["npm", "run", "dev"]

# CMD ["sleep", "900000000"]